import { Roboto } from 'next/font/google'
import './globals.css'
import Topbar from '../components/Topbar'
import Providers from './Providers'

const roboto = Roboto({ subsets: ['latin'], weight: ["400", "500", "700"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-800 text-white">
      <body className={roboto.className}>
        <Providers>
          <Topbar/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
